repos:
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8  # 🔄 Mudança para GitHub
    rev: 6.1.0
    hooks:
      - id: flake8

  - repo: local
    hooks:
      - id: mypy
        name: Run mypy
        entry: poetry run mypy
        language: system
        types: [python]


  - repo: local
    hooks:
      - id: pytest
        name: Run pytest tests
        entry: poetry run pytest tests/
        language: system
        pass_filenames: false
        types: [python]



