"""create movie_producer table

Revision ID: 596f21810b72
Revises: a1359d2ef5ec
Create Date: 2025-02-19 20:02:23.120615

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "596f21810b72"
down_revision: Union[str, None] = "a1359d2ef5ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movie_producer",
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("producer_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["producer_id"],
            ["producers.id"],
        ),
        sa.PrimaryKeyConstraint("movie_id", "producer_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movie_producer")
    # ### end Alembic commands ###
