"""add winner column to movies

Revision ID: cae7ecc61cac
Revises: 596f21810b72
Create Date: 2025-02-20 00:17:33.650231

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cae7ecc61cac"
down_revision: Union[str, None] = "596f21810b72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("movies", sa.Column("winner", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("movies", "winner")
    # ### end Alembic commands ###
