"""create movie_studio table

Revision ID: d2851158e412
Revises: e23037fbeb64
Create Date: 2025-02-20 01:59:48.838999

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d2851158e412"
down_revision: Union[str, None] = "e23037fbeb64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movie_studio",
        sa.Column("movie_id", sa.Integer(), nullable=False),
        sa.Column("studio_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["movie_id"],
            ["movies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["studio_id"],
            ["studios.id"],
        ),
        sa.PrimaryKeyConstraint("movie_id", "studio_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movie_studio")
    # ### end Alembic commands ###
