services:
  api:
    build:
      context: ../
      dockerfile: infrastructure/Dockerfile
    image: zuplae/golden-raspberry-awards-api 
    container_name: golden-raspberry-awards-api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./db.sqlite3
    command: ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
